# Generated by Django 2.1.2 on 2018-10-23 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome da atividade')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('inscricoes', models.ManyToManyField(blank=True, related_name='inscritos', to=settings.AUTH_USER_MODEL, verbose_name='inscrições')),
                ('palestrante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL, verbose_name='evento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do evento')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='criador')),
                ('lista_minicursos', models.ManyToManyField(blank=True, related_name='minicursos', to='sistema_eventos.Atividade')),
                ('lista_palestras', models.ManyToManyField(blank=True, related_name='palestras', to='sistema_eventos.Atividade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Palestrante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome', models.CharField(max_length=255, verbose_name='nome do palestrante')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
