# Generated by Django 2.1.2 on 2018-10-23 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='palestrante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='sistema_eventos.Palestrante', verbose_name='evento'),
        ),
    ]
